#!/usr/bin/env python3
"""Fill in ratings for newsletter and first 20 journal posts in post-audit.csv."""

import csv

# slug -> (originality, imagery, depth, structure, sentences, voice, pm_share, audience, relevance, action, notes)
RATINGS = {
    # Newsletter (all Public, all PM-shareable)
    "the-lens-edition-1-what-is-product-management": (6, 5, 5, 7, 7, 7, "Y", "P", 4, "Keep", "Good intro; InVideo support example is concrete"),
    "the-lens-edition-2-solving-ambiguous-problems-metrics": (7, 6, 7, 7, 7, 7, "Y", "P", 5, "Keep", "Context-as-leverage quote is memorable"),
    "the-lens-edition-3-pm-leadership-personal-vision-ephemeral-content": (6, 5, 7, 6, 7, 7, "Y", "P", 3, "Revise", "Fleets section is dated (Twitter deprecated Fleets in 2021)"),
    "the-lens-edition-4-compassionate-leadership-strategy": (8, 8, 8, 7, 8, 8, "Y", "P", 5, "Keep", "Grinch/Colonel story are memorable; Porter definition well applied"),
    "the-lens-edition-5-okrs": (6, 5, 7, 8, 8, 7, "Y", "P", 5, "Keep", "Cleanest structure in the series; output vs outcome distinction is sharp"),
    "the-lens-edition-6-books-i-read-in-2020": (5, 4, 4, 6, 7, 8, "Y", "P", 4, "Keep", "Most personal and authentic edition; still useful as a reading list"),
    "the-lens-edition-7-how-to-do-product-prioritization": (7, 7, 8, 8, 8, 7, "Y", "P", 5, "Keep", "Funny Girl and Netflix examples make abstract concepts concrete; best PM piece"),
    "the-lens-edition-8-knowing-your-users-types-of-pms": (7, 7, 7, 7, 7, 7, "Y", "P", 5, "Keep", "Starbucks Strategy / one-person focus tip is actionable"),
    "the-lens-edition-9-preventing-problems-tiers-of-engagement": (8, 6, 8, 7, 8, 7, "Y", "P", 5, "Keep", "Preventable Problem Paradox is a strong original concept"),
    "the-lens-edition-10-risk-reduction-working-with-engineering": (7, 6, 8, 8, 8, 8, "Y", "P", 5, "Keep", "Engineers as partners framing; download-your-brain metaphor is vivid"),
    "the-lens-edition-11-positioning": (8, 9, 7, 8, 8, 8, "Y", "P", 5, "Keep", "Best imagery in the series; Hot Cheetos + KitKat + muffin-vs-cake examples are excellent"),

    # Journal — 20 oldest posts (2004-2005, personal life in Bangalore)
    "trap-trip-report-and-analysis-pondicherry": (5, 5, 4, 4, 5, 7, "N", "F", 2, "Archive", "Personal trip report; warm voice but rough prose and encoding issues"),
    "ombattu-gudda": (5, 5, 4, 4, 5, 7, "N", "F", 2, "Archive", "Trek narrative; personal charm, not for public"),
    "yuva": (5, 5, 5, 5, 6, 6, "N", "F", 3, "Archive", "Bollywood review with some film craft observation"),
    "hum-tum": (6, 5, 4, 5, 5, 7, "N", "F", 2, "Archive", "Creative dialogue format shows personality; deeply personal"),
    "rangashankara-rehearsal": (5, 6, 5, 6, 6, 6, "N", "F", 2, "Archive", "Theatre visit write-up; decent descriptive writing"),
    "veer-zaara": (5, 5, 5, 5, 6, 6, "N", "F", 2, "Archive", "Film review; formula-driven but competent"),
    "launch": (4, 4, 4, 5, 5, 7, "N", "A", 3, "Archive", "First blog announcement post; historically interesting"),
    "oxymoronica": (5, 5, 6, 5, 5, 6, "N", "F", 3, "Archive", "Book response; shows intellectual curiosity"),
    "munnar-and-ootywhich-comes-on-the-way": (5, 6, 4, 5, 5, 6, "N", "F", 2, "Archive", "Travel log; good detail but personal"),
    "my-daily-happenings": (6, 4, 4, 4, 6, 7, "N", "F", 2, "Archive", "Dry humor piece about routine; charming brevity"),
    "g-simplicity": (5, 4, 5, 4, 5, 6, "N", "F", 3, "Archive", "Early Google take; dated but shows product thinking emerging"),
    "oo-aa-ouch": (3, 3, 2, 3, 4, 5, "N", "A", 1, "Archive", "One-liner about sprained leg; no substance"),
    "rangashankara-the-final-rehearsal": (5, 6, 5, 5, 6, 6, "N", "F", 2, "Archive", "Theatre review; better than the first rehearsal post"),
    "on-my-way-beat": (7, 6, 5, 7, 6, 7, "N", "F", 3, "Archive", "Best writing in this batch — stream-of-consciousness rhythm works"),
    "what-do-i-do": (5, 4, 4, 5, 5, 6, "N", "A", 2, "Archive", "Overwhelm list; personal, no public value"),
    "club-experience": (5, 5, 4, 5, 5, 6, "N", "F", 2, "Archive", "Friend's club visit told second-hand; light"),
    "packed-weekend": (4, 4, 4, 4, 5, 6, "N", "A", 2, "Archive", "Weekend recap; thin content"),
    "see-me": (2, 2, 1, 2, 3, 4, "N", "A", 1, "Delete", "Just a photo placeholder; no content"),
    "blogging": (5, 4, 5, 5, 5, 5, "N", "F", 2, "Archive", "2004 blogging zeitgeist piece; now dated"),
    "desk-top": (4, 4, 3, 3, 5, 6, "N", "A", 1, "Archive", "Desk description; ephemeral slice of life, no lasting value"),
}

# slug -> same tuple shape, for the 113 journal posts tagged with a WordPress
# review category (Movie Reviews, Book Review, Play Review, Movie talk). Rated
# for public-safety rather than professional polish: genuine movie/book/play
# critique is Keep+P even when dated or unpolished; personal/fan-crush drift
# and thin one-liners are F/A. Overrides the 6 review posts already rated above
# (yuva, hum-tum, rangashankara-rehearsal, veer-zaara, oxymoronica,
# rangashankara-the-final-rehearsal), which had been marked F/Archive under a
# stricter professional-polish read.
REVIEW_RATINGS = {
    "yuva": (6, 7, 6, 6, 5, 7, "N", "P", 4, "Keep", "Manirathnam ensemble drama; balanced critique of the three interwoven threads"),
    "hum-tum": (6, 7, 6, 6, 5, 7, "N", "P", 4, "Keep", "Inventive dialogue-format review of Yash Chopra's Hum Tum"),
    "rangashankara-rehearsal": (6, 7, 6, 6, 5, 7, "N", "P", 4, "Keep", "RangaShankara venue profile and tribute to Shankar Nag"),
    "veer-zaara": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Even-handed Veer-Zaara critique, DDLJ comparison"),
    "oxymoronica": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Thoughtful review of Grothe's Oxymoronica quote collection"),
    "rangashankara-the-final-rehearsal": (6, 7, 6, 6, 5, 7, "N", "P", 4, "Keep", "Play review, The Final Rehearsal; praises the single-actor performance"),
    "da-vinci-code": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Da Vinci Code review structured by theme"),
    "iti-ninna-amritha": (6, 7, 6, 6, 5, 7, "N", "P", 4, "Keep", "Epistolary play review, praises Arundathi Nag's performance"),
    "who-moved-my-cheese": (5, 5, 5, 5, 5, 6, "Y", "P", 3, "Keep", "Reflective business-fable review with personal follow-up questions"),
    "7g": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Critical take on 7G Rainbow Colony's stalker-as-romance plot"),
    "a-heap-of-broken-images": (6, 7, 6, 6, 5, 7, "N", "P", 4, "Keep", "Girish Karnad play review, praises Arundathi Raja's solo performance"),
    "aptha-mitra": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Detailed Kannada horror-thriller review, tribute to Soundarya"),
    "kajol": (3, 3, 3, 3, 4, 5, "N", "F", 2, "Archive", "Fan post about an actress's endorsements/upcoming film, not review content"),
    "rangashankara-sleuth": (6, 7, 6, 6, 5, 7, "N", "P", 4, "Keep", "Sleuth play review with vivid audience-experience color"),
    "85": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Parineeta review, praises Vidya Balan's debut"),
    "sarkar": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "RGV's Sarkar weighed against Satya, well-argued"),
    "sahara": (3, 3, 3, 3, 4, 5, "N", "P", 2, "Keep", "Short, honest take on a forgettable film"),
    "war-of-the-worlds": (3, 3, 3, 3, 4, 5, "N", "P", 2, "Keep", "Short critique of plot vs technical spectacle"),
    "funtastic-four": (3, 3, 3, 3, 4, 5, "N", "P", 2, "Keep", "Short, self-aware take on a popcorn movie"),
    "thanks-pooja": (3, 3, 3, 3, 4, 5, "N", "A", 2, "Archive", "One-line joke, no real content"),
    "coincidences-ab-jr-shelved-fanah": (3, 3, 3, 3, 4, 5, "N", "F", 2, "Archive", "Industry gossip mixed with fan commentary"),
    "holiweek": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Multi-movie roundup review from a week off"),
    "jogi-a-feel-that-never-ends": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Kannada thriller review, praises lead performance and direction"),
    "iqbal": (6, 7, 6, 6, 5, 7, "N", "P", 4, "Keep", "Warm, detailed review of Iqbal's underdog-cricket story"),
    "a-life-lived": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Review of Feynman biography, admiring but critical of one chapter"),
    "weekend-movies-2": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Comparative review of two weekend releases"),
    "sankranti": (6, 7, 6, 6, 5, 7, "N", "P", 4, "Keep", "Detailed play review, praises lead performances"),
    "some-miss-some-hits": (3, 3, 3, 3, 4, 5, "N", "F", 2, "Archive", "Personal weekend diary (bloggers' meetup) with a passing movie mention"),
    "the-myth": (3, 3, 3, 3, 4, 5, "N", "P", 2, "Keep", "Short Jackie Chan movie review, self-aware about language barrier"),
    "apaharan": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Kidnap-drama review, praises performances over plot"),
    "ek-ajnabee": (3, 3, 3, 3, 4, 5, "N", "A", 2, "Archive", "One-line joke about a spoiler-heavy trailer"),
    "india-questions-aamir-khan": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Detailed recap/commentary on a televised interview"),
    "a-general-roundup": (3, 3, 3, 3, 4, 5, "N", "F", 2, "Archive", "Personal life update (talks, books, movies) mixed together"),
    "ab-baby": (3, 3, 3, 3, 4, 5, "N", "F", 2, "Archive", "Thin fan musing ranking two actors' years"),
    "rang-de-basanti": (6, 7, 6, 6, 5, 7, "N", "P", 4, "Keep", "Well-structured Rang De Basanti review, strong observations"),
    "all-the-best": (6, 7, 6, 6, 5, 7, "N", "P", 4, "Keep", "Vivid account of a comedy play and its audience"),
    "9211": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Genre-aware critique using a 'popcorn film' framework"),
    "%e0%b2%ac%e0%b2%82%e0%b2%97%e0%b2%be%e0%b2%b0%e0%b2%a6-%e0%b2%ae%e0%b2%a8%e0%b3%81%e0%b2%b7%e0%b3%8d%e0%b2%af-%e0%b2%87%e0%b2%a8%e0%b3%8d%e0%b2%a8%e0%b2%bf%e0%b2%b2%e0%b3%8d%e0%b2%b2": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Tribute to actor Dr Rajkumar on his passing"),
    "being-cyrus-zathura": (3, 3, 3, 3, 4, 5, "N", "P", 2, "Keep", "Short double review of two films"),
    "crash": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Thoughtful review of Crash's ensemble structure and themes"),
    "my-autograph": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Review of Sudeep's directorial debut, praises the script"),
    "fanaaa": (3, 3, 3, 3, 4, 5, "N", "F", 2, "Archive", "Promo links and fan excitement, no review content"),
    "gangster-a-love-story": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Review praising Kangana Ranaut's debut performance"),
    "shantaram": (6, 7, 6, 6, 5, 7, "N", "P", 4, "Keep", "Long-form reflective book review of Shantaram"),
    "fanaa": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Critical review of Fanaa's script despite fan enthusiasm for the lead"),
    "chup-chup-ke": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Comedic, critical review of a three-story film"),
    "hayavadana": (6, 7, 6, 6, 5, 7, "N", "P", 4, "Keep", "Detailed retelling and review of Girish Karnad's Hayavadana"),
    "first-impressions-of-kank": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Review comparing KANK's cast choices and performances"),
    "krrish-cyanideomkarasomething-somethingvettaiyaadu": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Multi-film roundup review"),
    "man-who-knew-infinity-abachurina-post-office-toofan-mail": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Book review roundup: Ramanujan biography and two story collections"),
    "nenapirali": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Kannada romance review, technical craft praised"),
    "lage-raho-munnabhai": (6, 7, 6, 6, 5, 7, "N", "P", 4, "Keep", "Enthusiastic, detailed Lage Raho Munna Bhai review"),
    "pksedorkkg": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Curated excerpts of other critics' reviews with commentary"),
    "kajol-as-sita": (3, 3, 3, 3, 4, 5, "N", "F", 2, "Archive", "Thin fan joke about casting news"),
    "zindagi-rocks": (3, 3, 3, 3, 4, 5, "N", "A", 2, "Archive", "Just quotes another blogger's joke, minimal original content"),
    "dor": (6, 7, 6, 6, 5, 7, "N", "P", 4, "Keep", "Detailed, admiring review of Dor's performances and dialogue"),
    "woh-lamhe": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Short review built around critic quotes, praises Kangana Ranaut"),
    "jote-joteyalikkgdonumrao-jaan": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Multi-film roundup with numbered observations"),
    "dhoom-2": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Curated critic quotes plus own critical take on Dhoom 2"),
    "thank-you-note": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Nostalgic essay on how a college friendship shaped a love of movies"),
    "movie-mela": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Film festival roundup, several short reviews"),
    "kafkas-metamorphosis": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Reflective review of Kafka's Metamorphosis and its author"),
    "guru": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Balanced Guru review via a chat transcript"),
    "koffee-main-tum-aur-hum-ravana": (3, 3, 3, 3, 4, 5, "N", "F", 2, "Archive", "Celebrity gossip roundup, not review content"),
    "united-93": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Short, sober review of United 93"),
    "atlas-shrugged": (6, 7, 6, 6, 5, 7, "Y", "P", 4, "Keep", "Long, personal reflection on reading Atlas Shrugged"),
    "happy-feet": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Detailed, affectionate Happy Feet review"),
    "mungaru-male": (6, 7, 6, 6, 5, 7, "N", "P", 4, "Keep", "Long-form Mungaru Male review via DDLJ comparison"),
    "duniya": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Review of Duniya Vijay's breakout performance"),
    "rangashankara-sankramana": (6, 7, 6, 6, 5, 7, "N", "P", 4, "Keep", "Detailed review of a two-hander play, praises staging"),
    "vertigo": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Review of a Hitchcock screening event plus the film itself"),
    "bheja-fry": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Enthusiastic Bheja Fry review, praises Vinay Pathak"),
    "heegadre-hege": (3, 3, 3, 3, 4, 5, "N", "P", 2, "Keep", "Short review of a comedic play anthology"),
    "just-what-i-wanted-to-say-2": (3, 3, 3, 3, 4, 5, "N", "P", 2, "Keep", "Reflection on watching movies alone, references another blog post"),
    "salaam-e-ishq-black-friday-in-pursuit": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Multi-film roundup with comparative notes"),
    "rangashankara-mallinatha-dhyana": (6, 7, 6, 6, 5, 7, "N", "P", 4, "Keep", "Detailed review of a three-story anthology play"),
    "life-in-a-metro": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Review built around another critic's take, plus original points"),
    "rangashankara-maduve-maduve": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Musical play review, mixed but fair assessment"),
    "himesh-shows-signs-of-becoming-rajinikanth": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Commentary on a surprise box-office hit via critic quotes"),
    "aap-ka-suroor-or-rather-himesh-reshammiyas-topi-2": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Review of a singer-actor's box-office debut"),
    "rangashankara-neenaanaadrenaaneenena": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Comedy-of-errors play review, references source material"),
    "mini-book-reviews": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Roundup of three Kannada book reviews"),
    "satyavan-savitri": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Remake review, compares to source film"),
    "cheeni-kum": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Review praising Tabu and the film's central relationship"),
    "jhoom-barabar-jhoom": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Enthusiastic review defending a panned film"),
    "honeymoon-travels-pvt-ltd": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Detailed multi-story ensemble film review"),
    "chak-de": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Enthusiastic Chak De India review, notes the real-story basis"),
    "checkmate-rangashankara": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Thriller play review, notes performance flaws"),
    "to-kill-a-mocking-bird": (6, 7, 6, 6, 5, 7, "N", "P", 4, "Keep", "Reflective book review, notes on structure and themes"),
    "heyy-babyy": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Critical review of a comedy film's reliance on trailer gags"),
    "kane-and-abel-jeffry-archer": (6, 7, 6, 6, 5, 7, "N", "P", 4, "Keep", "Long, detailed Kane and Abel book review"),
    "random-bursts-of-thoughts-and-happenings-2nd-edition-3-2": (3, 3, 3, 3, 4, 5, "N", "F", 2, "Archive", "Personal life update (tech, travel, work) with passing movie mentions"),
    "manorama-six-feet-under": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Enthusiastic, concise review of a debut thriller"),
    "cinema-halls": (3, 3, 3, 3, 4, 5, "N", "P", 2, "Keep", "Personal essay about multiplex-going habits in Bangalore"),
    "jodha-akbar": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Critical review of Jodha Akbar's romance-over-history balance"),
    "u-me-aur-hum-2-2": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Review of a film built around a fan's admiration for the lead actress"),
    "it-aint-about-how-hard-you-hit": (3, 3, 3, 3, 4, 5, "N", "A", 2, "Archive", "Just a Rocky quote, no original content"),
    "i-dont-know-what-im-supposed-to-be-2-2": (3, 3, 3, 3, 4, 5, "N", "A", 2, "Delete", "Exact duplicate of another post"),
    "i-dont-know-what-im-supposed-to-be-2": (3, 3, 3, 3, 4, 5, "N", "A", 2, "Archive", "Just a Lost in Translation quote, minimal original content"),
    "little_miss_sunshine": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Reflective review built around film quotes"),
    "the_shawshank_redemption": (6, 7, 6, 6, 5, 7, "N", "P", 4, "Keep", "Long, detailed Shawshank Redemption review"),
    "rock-on": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Enthusiastic Rock On review, praises Farhan Akhtar"),
    "lyrics-time": (3, 3, 3, 3, 4, 5, "N", "F", 2, "Archive", "Song lyrics dedicated to a specific person; personal, not review content"),
    "sorry-bhai": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Warm review of an ensemble relationship comedy"),
    "common-man": (6, 7, 6, 6, 5, 7, "N", "P", 4, "Keep", "Detailed, moving review of a wordless play"),
    "dance_festiva": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Dance festival review, two performances described"),
    "all-you-need-is-love": (6, 7, 6, 6, 5, 7, "N", "P", 4, "Keep", "Detailed review of an interactive playback-theatre show"),
    "milkshake_before_sunrise": (3, 3, 3, 3, 4, 5, "N", "P", 2, "Keep", "Personal reflection anchored to a favorite film, Before Sunrise"),
    "sadarame-rangashankara": (6, 7, 6, 6, 5, 7, "N", "P", 4, "Keep", "Detailed folk-play review, praises lead performances"),
    "all-things-inception": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Reflective Inception review, engages with fan theories"),
    "movies-in-usa": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Essay comparing US and India moviegoing experiences"),
    "o-saathi-re": (3, 3, 3, 3, 4, 5, "N", "P", 2, "Keep", "Short appreciation of a classic film scene"),
    "happiness-is-beautiful-birds-singing": (5, 5, 5, 5, 5, 6, "N", "P", 3, "Keep", "Descriptive review of a short film/ad about a farming family"),
}

# slug -> same tuple shape, for the 178 posts in /notes/ (2018-2020 curated
# link-blog era). Unlike the old wp_ journal, these were never marked
# WordPress-private -- they were already the live public blog -- so almost
# all are Keep+P by default. Exceptions: two posts reveal personal family
# history (marriage, child's birth, a health emergency) and are kept F;
# ~20 empty/broken import artifacts are Delete; ~25 bare-link bookmarks with
# no commentary are Archive.
NOTES_RATINGS = {
    "pm-resources": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "pondering-about-job-culture-values": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "43": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "https-youtu-be-ujzpjbmqfy4": (2, 2, 2, 2, 3, 3, "N", "A", 1, "Archive", "Bare link bookmark, no commentary"),
    "had-a-great-weekend-bbq": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "55": (4, 3, 3, 3, 4, 4, "N", "P", 2, "Keep", "Link-only note; content was hidden by a wplinkpreview shortcode bug in the build script, now fixed"),
    "__trashed": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "59": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "61": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "listening": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "72": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "dont-make-me-think": (2, 2, 2, 2, 3, 3, "N", "A", 1, "Archive", "Bare link bookmark, no commentary"),
    "this-clever-app-lets-amazon-alexa-read-sign-language": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "20-vibrant-photos-with-high-color-contrast": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "kindness": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "starting-august-1-you-can-3d-print-a-gun": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "new-uscis-policy-will-carry-harsh-consequences-for-applicants": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "uscis-updates-policy-guidance-for-certain-requests-for-evidence-and-notices-of-intent-to-deny-uscis": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "underground-railroad-wikipedia": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "when-will-outlook-gets-some": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "facebooks-free-food-banned-as-silicon-valley-restaurants-hit-back": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "listened-to-black-holes-exponent": (2, 2, 2, 2, 3, 3, "N", "A", 1, "Archive", "Bare link bookmark, no commentary"),
    "caliphate-podcast": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "gender-confidence-gap": (2, 2, 2, 2, 3, 3, "N", "A", 1, "Archive", "Bare link bookmark, no commentary"),
    "google-unveils-2fa-titan-security-key-w-custom-firmware-coming-to-google-store": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "113": (4, 3, 3, 3, 4, 4, "N", "P", 2, "Keep", "Link-only note; content was hidden by a wplinkpreview shortcode bug in the build script, now fixed"),
    "115": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "117": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "watching": (2, 2, 2, 2, 3, 3, "N", "A", 1, "Archive", "Bare link bookmark, no commentary"),
    "facebook-stock": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "alexa-skill-invocation-name": (4, 3, 3, 3, 4, 4, "N", "P", 2, "Keep", "Link-only note; content was hidden by a wplinkpreview shortcode bug in the build script, now fixed"),
    "useloom-com-is-awesome-what": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "pondering-over-the-question": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "i-have-to-check-some": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "listening-to-john-maxwell-on": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "moviepass-in-crisis": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "138": (4, 3, 3, 3, 4, 4, "N", "P", 2, "Keep", "Link-only note; content was hidden by a wplinkpreview shortcode bug in the build script, now fixed"),
    "watching-2": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "comcast-business-clicked-on": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "so-sad-that-moves-app": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "watching-count-of-monte-cristo": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "146": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "eu-fines-google": (4, 3, 3, 3, 4, 4, "N", "P", 2, "Keep", "Link-only note; content was hidden by a wplinkpreview shortcode bug in the build script, now fixed"),
    "148": (4, 3, 3, 3, 4, 4, "N", "P", 2, "Keep", "Link-only note; content was hidden by a wplinkpreview shortcode bug in the build script, now fixed"),
    "virtual-numbers-on-capital-one": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "movies": (2, 2, 2, 2, 3, 3, "N", "A", 1, "Archive", "Bare link bookmark, no commentary"),
    "first-round-capital-on-employee-motivation": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "til": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "mission-impossible": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "from-the-top": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "beautiful-video-from-bbc-earth": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "160": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "162": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "164": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "165": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "166": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "167": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "honey": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "facebook-login-page-design-optimization": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "pm-differences": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "184": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "fee-free-fund": (2, 2, 2, 2, 3, 3, "N", "A", 1, "Archive", "Bare link bookmark, no commentary"),
    "fairness": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "roywood-jr": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "get-better-by-todd-davis": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "are-the-stars-you-see-in-the-sky-already-dead": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "tweetorder-com-jed-christiansen": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "tweetorder": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "get-compensation-for-flight-delays-of-up-to-700-airhelp": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "the-vest-vending-machine-at-san-franciscos-airport-is-making-bank-business-insider": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "212": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "213": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "cbs-ceo": (4, 3, 3, 3, 4, 4, "N", "P", 2, "Keep", "Link-only note; content was hidden by a wplinkpreview shortcode bug in the build script, now fixed"),
    "sticher-the-leader": (4, 3, 3, 3, 4, 4, "N", "P", 2, "Keep", "Link-only note; content was hidden by a wplinkpreview shortcode bug in the build script, now fixed"),
    "moviepass-update": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "prime-on-comcast": (4, 3, 3, 3, 4, 4, "N", "P", 2, "Keep", "Link-only note; content was hidden by a wplinkpreview shortcode bug in the build script, now fixed"),
    "how-to-disagree": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "watching-3": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "opinion-make-your-daughter-practice-math-shell-thank-you-later-the-new-york-times": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "mobile-friendly-pdf": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "ticket-to-ride-ai": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "mr-smith-goes-to-washington": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "dr-strangelove": (2, 2, 2, 2, 3, 3, "N", "A", 1, "Archive", "Bare link bookmark, no commentary"),
    "jedi": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "ceo-to-vp-of-products": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "indra-nooyi": (4, 3, 3, 3, 4, 4, "N", "P", 2, "Keep", "Link-only note; content was hidden by a wplinkpreview shortcode bug in the build script, now fixed"),
    "249": (4, 3, 3, 3, 4, 4, "N", "P", 2, "Keep", "Link-only note; content was hidden by a wplinkpreview shortcode bug in the build script, now fixed"),
    "250": (4, 3, 3, 3, 4, 4, "N", "P", 2, "Keep", "Link-only note; content was hidden by a wplinkpreview shortcode bug in the build script, now fixed"),
    "251": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "design-lessons-from-silicon-valleys-most-important-failure": (4, 3, 3, 3, 4, 4, "N", "P", 2, "Keep", "Link-only note; content was hidden by a wplinkpreview shortcode bug in the build script, now fixed"),
    "the-hierarchy-of-disagreement-the-best-and-worst-argument-techniques-big-think": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "opinion-make-your-daughter-practice-math-shell-thank-you-later-the-new-york-times-2": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "cryptokitties-the-download-on-digital-cats-planet-money-npr": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "hey-google-tell-me-something-good": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "stand-ups-are-broken": (4, 3, 3, 3, 4, 4, "N", "P", 2, "Keep", "Link-only note; content was hidden by a wplinkpreview shortcode bug in the build script, now fixed"),
    "north-by-north-west": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "grande": (4, 3, 3, 3, 4, 4, "N", "P", 2, "Keep", "Link-only note; content was hidden by a wplinkpreview shortcode bug in the build script, now fixed"),
    "science-fiction-readers": (4, 3, 3, 3, 4, 4, "N", "P", 2, "Keep", "Link-only note; content was hidden by a wplinkpreview shortcode bug in the build script, now fixed"),
    "product-comparison": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "postmortems-in-development": (4, 3, 3, 3, 4, 4, "N", "P", 2, "Keep", "Link-only note; content was hidden by a wplinkpreview shortcode bug in the build script, now fixed"),
    "insurance-comparison": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "crappy-design": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "walmarts-latest-move-to-compete-with-amazon-is-a-kobo-ebook-and-audiobook-store-the-verge": (2, 2, 2, 2, 3, 3, "N", "A", 1, "Archive", "Bare link bookmark, no commentary"),
    "how-to-persuade-your-companys-product-team-to-build-something-quartz-at-work": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "is-coconut-oil-bad-for-you-a-professor-called-it-poison-vox": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "mental-models-for-pms": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "quest-lab-self-check-in": (4, 3, 3, 3, 4, 4, "N", "P", 2, "Keep", "Link-only note; content was hidden by a wplinkpreview shortcode bug in the build script, now fixed"),
    "evernote-rebranding": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "how-to-be-a-hero": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "why-technical-experts-make-great-leaders-podcast": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "294": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "fire-in-brazils-national-museum": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "298": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "lost-kitchen": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "tee-wisdom": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "how-energy-makes-life-possible-bill-gates": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "working-on-a-problem-separately": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "decision-making": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "making-friends": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "a-better-way": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "naming": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "sting": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "index-funds": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "podcast-day": (4, 3, 3, 3, 4, 4, "N", "P", 2, "Keep", "Link-only note; content was hidden by a wplinkpreview shortcode bug in the build script, now fixed"),
    "google-assistant-redesign-adds-bigger-visuals-simple-smart-home-control": (2, 2, 2, 2, 3, 3, "N", "A", 1, "Archive", "Bare link bookmark, no commentary"),
    "hobby": (4, 3, 3, 3, 4, 4, "N", "P", 2, "Keep", "Link-only note; content was hidden by a wplinkpreview shortcode bug in the build script, now fixed"),
    "dominos-self-driving-car": (2, 2, 2, 2, 3, 3, "N", "A", 1, "Archive", "Bare link bookmark, no commentary"),
    "google-plus": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "2-3rd": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "336": (4, 3, 3, 3, 4, 4, "N", "P", 2, "Keep", "Link-only note; content was hidden by a wplinkpreview shortcode bug in the build script, now fixed"),
    "how-mapping-the-agile-transformation-journey-points-the-way-to-continuous-innovation": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "avoiding-the-wrong-mvp-approach-jared-m-spool-medium": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "how-mental-models-unlock-your-thinking": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "spotify-freakonomics-podcast": (2, 2, 2, 2, 3, 3, "N", "A", 1, "Archive", "Bare link bookmark, no commentary"),
    "341": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "compaq-how-i-built-this": (2, 2, 2, 2, 3, 3, "N", "A", 1, "Archive", "Bare link bookmark, no commentary"),
    "logic-how-i-built-this": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "squarespace-how-i-built-this": (2, 2, 2, 2, 3, 3, "N", "A", 1, "Archive", "Bare link bookmark, no commentary"),
    "debugging-mazda-defect": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "spotify": (2, 2, 2, 2, 3, 3, "N", "A", 1, "Archive", "Bare link bookmark, no commentary"),
    "the-greatest-coach-silicon-valley-product-group": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "stewart-butterfield": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "daymond-john": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "data-driven-guide-to-sane-parenting": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "luck-risk-and-avoiding-losers": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "goal-mining": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "rani-lakshmi-bai": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "taxes": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "creating-god": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "sensationalism-in-news": (2, 2, 2, 2, 3, 3, "N", "A", 1, "Archive", "Bare link bookmark, no commentary"),
    "likership": (2, 2, 2, 2, 3, 3, "N", "A", 1, "Archive", "Bare link bookmark, no commentary"),
    "we-chat": (2, 2, 2, 2, 3, 3, "N", "A", 1, "Archive", "Bare link bookmark, no commentary"),
    "retirement": (2, 2, 2, 2, 3, 3, "N", "A", 1, "Archive", "Bare link bookmark, no commentary"),
    "referrals": (2, 2, 2, 2, 3, 3, "N", "A", 1, "Archive", "Bare link bookmark, no commentary"),
    "remote-work-resources": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "390": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "392": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "393": (2, 2, 2, 2, 3, 3, "N", "A", 1, "Archive", "Bare link bookmark, no commentary"),
    "tips-on-isolation-by-scott-kelly": (2, 2, 2, 2, 3, 3, "N", "A", 1, "Archive", "Bare link bookmark, no commentary"),
    "links-and-resources-for-parents": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "world-2-0-there-are-decades-where-nothing-happens-and-weeks-where-decades-happen-marginal-revolution": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "sultan-khan": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "rabbit-hole": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "cooking": (5, 5, 5, 5, 5, 6, "N", "F", 2, "Archive", "Personal life narrative (health emergency / family history)"),
    "twitter": (1, 1, 1, 1, 1, 1, "N", "A", 1, "Hide", "Image-only post, no text; excluded from the build via HIDDEN_SLUGS in extract_posts.py rather than deleted"),
    "pluto-tv-ilya-pozen": (2, 2, 2, 2, 3, 3, "N", "A", 1, "Archive", "Bare link bookmark, no commentary"),
    "how-this-video-applies-to-any-context": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "regrets-of-the-dying-bronnie-ware": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "how-to-organize-information": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "how-to-praise-your-co-worker-correctly": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "my-experience-with-911": (5, 5, 5, 5, 5, 6, "N", "F", 2, "Archive", "Personal life narrative (health emergency / family history)"),
    "newsletter-launch": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "pms-as-enablers-of-decisions": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "about-state-college": (2, 2, 2, 2, 3, 3, "N", "A", 1, "Archive", "Bare link bookmark, no commentary"),
    "micro-moments": (2, 2, 2, 2, 3, 3, "N", "A", 1, "Archive", "Bare link bookmark, no commentary"),
    "building-products-in-a-heavily-regulated-space": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "rise-of-tech-enabled-services": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
    "book-recommendations": (5, 4, 4, 4, 5, 5, "N", "P", 3, "Keep", "Public-safe link-blog note (curated links/thoughts, 2018-2020)"),
}

RATINGS.update(REVIEW_RATINGS)

# A few slugs are reused across sections (e.g. "165", "movies" exist in both
# notes and wedding). NOTES_RATINGS is only ever applied to section == "notes"
# rows below, so those collisions can't leak into the wrong section.

rows = []
with open("post-audit.csv", "r", encoding="utf-8") as f:
    reader = csv.DictReader(f)
    fieldnames = reader.fieldnames
    for row in reader:
        slug = row["slug"]
        section = row["section"]
        if section == "notes" and slug in NOTES_RATINGS:
            r = NOTES_RATINGS[slug]
        elif slug in RATINGS:
            r = RATINGS[slug]
        else:
            r = None
        if r:
            row["originality"] = r[0]
            row["imagery"] = r[1]
            row["philosophical_depth"] = r[2]
            row["structure"] = r[3]
            row["sentence_control"] = r[4]
            row["voice"] = r[5]
            row["pm_share"] = r[6]
            row["audience"] = r[7]
            row["relevance"] = r[8]
            row["action"] = r[9]
            row["notes"] = r[10]
        rows.append(row)

with open("post-audit.csv", "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(rows)

rated = sum(1 for r in rows if r["action"])
print(f"Rated {rated} / {len(rows)} posts")
